# application.yml - Base

# --- Server Configuration
server:
  port: ${APP_PORT:8081}

# --- Spring Configuration
spring:
  # --- Application
  application:
    name: Identity Profiles
    version: 1.0.0
  # --- Profiles
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2,dev}

# --- Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: ALWAYS
