# application-dev.yml (H2 Database)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:identity_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration/h2