# application.yml
# Identity Profiles - Gestão de Perfis
server:
  port: 8081
  servlet:
    context-path: /identity-profiles

spring:
  application:
    name: identity-profiles
  profiles:
    active:
      - dev
  jackson:
    serialization:
      indent-output: true
  cloud:
    discovery:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration/h2 # para dev (H2)
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org.springframework.cloud: INFO
    org.springframework.boot: INFO