spring:
  # --- Database H2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${DB_H2_NAME:testdb};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DB_H2_USER:sa}
    password: ${DB_H2_PASS:}
  # --- JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
