create table audit_log (
    id bigint generated by default as identity,
    action varchar(20) not null,
    details clob,
    entity varchar(100) not null,
    entity_id bigint not null,
    performed_by varchar(100) not null,
    timestamp timestamp(6) not null,
    primary key (id)
)
create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id)
)
create table users (
    id bigint generated by default as identity,
    created_at timestamp(6),
    email varchar(150) not null,
    full_name varchar(150) not null,
    password varchar(255) not null,
    status enum ('ACTIVE','BLOCKED','INACTIVE') not null,
    updated_at timestamp(6),
    username varchar(50) not null,
    primary key (id)
)

alter table if exists users
   drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7

alter table if exists users
   add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email)

alter table if exists users
   drop constraint if exists UKr43af9ap4edm43mmtq01oddj6

alter table if exists users
   add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username)

alter table if exists user_roles
   add constraint FKh8ciramu9cc9q3qcqiv4ue8a6
   foreign key (role_id)
   references roles

alter table if exists user_roles
   add constraint FKhfh9dx7w3ubf1co1vdev94g3f
   foreign key (user_id)
   references users