#version: "3.9"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service-prod
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql-prod
    command: sh -c "java $JAVA_OPTS -jar app.jar"

  mysql-prod:
    image: mysql:8
    container_name: mysql-prod
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql

volumes:
  mysql_prod_data: