# identity-access-domain/docker-compose.yml
services:
  eureka-server:
    image: eureka-server
    build: ../infra-domain/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - taptrack-net

  identity-profiles:
    image: identity-profiles
    build: ./identity-profiles
    container_name: identity-profiles
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev,h2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - taptrack-net

networks:
  taptrack-net:
    driver: bridge
