-- V001_create_roles.sql

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

INSERT INTO roles (name, description) VALUES
('ADMIN', 'System administrator with full access'),
('CUSTOMER', 'End customer with restricted access'),
('SUPPLIER', 'Supplier user with specific permissions'),
('MANAGER', 'Manager with supervisory permissions');
