-- V002__create_users.sql
-- Criação da tabela users
-- Compatível com MySQL e H2

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    full_name VARCHAR(150) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE','BLOCKED','INACTIVE'))
);

ALTER TABLE users
    ADD CONSTRAINT UK_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT UK_users_username UNIQUE (username);
