-- V004__create_audit_log.sql
-- Criação da tabela audit_log para registrar ações do sistema

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(20) NOT NULL,
    details CLOB,
    entity VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    performed_by VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_auditlog_entity ON audit_log (entity);
CREATE INDEX idx_auditlog_timestamp ON audit_log (timestamp);
