# application-prod.yml
# --- Prod Configuration ---
#
spring:
  # MySQL Database Configuration
  datasource:
    #    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin # ${DB_USER}
    password: root123 # ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  # Elasticsearch Configuration
  elasticsearch:
    # ${ELASTIC_HOST:localhost}:${ELASTIC_PORT:9200}
    uris: localhost:9200
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration

logging:
  level:
    root: INFO
    com.identityaccessdomain.userservice: INFO
