# application.yml
# --- Configuration ---
#
server:
  port: 8081 # ${APP_PORT:8081}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service
  # Profile ativo por default (local)
  profiles:
    active: prod

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS

# --- Logging ---
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.identityaccessdomain.userservice: DEBUG
    org.springframework.cache: DEBUG

# --- Info ---
info:
  app:
    name: ${spring.application.name}
    description: User Service do sistema TapTrack
    version: 0.0.1-SNAPSHOT
    maintainer: Juliane Maran
    contact: julianemaran@gmail.com

# --- SpringDoc OpenAPI Configuration
springdoc:
  # localhost:8080/api/v1/api-docs
  api-docs:
    path: /api-docs
    version: openapi_3_1
  # localhost:8080/api/v1/swagger-ui.html
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: "application/json"
  default-produces-media-type: "/"


debug: true