# application-local.yml
# --- Local Configuration ---
#
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  elasticsearch:
    uris: localhost:9200

logging:
  level:
    root: DEBUG
    com.identityaccessdomain.userservice: DEBUG
