# application-prod.yml
# --- Prod Configuration ---
#
#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/usersdb
#    driver-class-name: org.postgresql.Driver
#    username: ${DB_USER}
#    password: ${DB_PASS}
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: false
#        dialect: org.hibernate.dialect.PostgreSQLDialect

# Ajustes de logging específicos para produção
logging:
  level:
    root: INFO
    com.identityaccessdomain.userservice: INFO
