openapi: 3.0.3
info:
  title: User Service API
  description: API de gerenciamento de usuários (CRUD) do User Service.
  version: 1.0.0
servers:
  - url: http://localhost:8081/api/v1
    description: Local environment
paths:
  /users:
    get:
      summary: Listar todos os usuários
      operationId: listUsers
      responses:
        '200':
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponseDTO'
    post:
      summary: Cadastrar um usuário
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDTO'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
        '400':
          description: Erro de validação
  /users/{userId}:
    get:
      summary: Buscar usuário por ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
        '404':
          description: Usuário não encontrado
    put:
      summary: Atualizar usuário
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDTO'
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
        '404':
          description: Usuário não encontrado
    patch:
      summary: Atualizar usuário parcialmente
      operationId: partialUpdateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDTO'
      responses:
        '200':
          description: Usuário atualizado parcialmente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
        '404':
          description: Usuário não encontrado
    delete:
      summary: Excluir usuário
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Usuário excluído com sucesso
        '404':
          description: Usuário não encontrado
components:
  schemas:
    UserRequestDTO:
      type: object
      required:
        - firstName
        - lastName
        - email
      properties:
        firstName:
          type: string
          minLength: 3
          maxLength: 50
          example: Juliane
        lastName:
          type: string
          minLength: 3
          maxLength: 150
          example: Maran
        email:
          type: string
          format: email
          maxLength: 150
          example: juliane@example.com
    UserResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        firstName:
          type: string
          example: Alice
        lastName:
          type: string
          example: Silva
        email:
          type: string
          example: alice@example.com
